// Code generated by mockery v1.0.0. DO NOT EDIT.

package httpparsermocks

import context "context"
import http "net/http"

import mock "github.com/stretchr/testify/mock"

// HttpParseriface is an autogenerated mock type for the HttpParseriface type
type HttpParseriface struct {
	mock.Mock
}

// HTTPGet provides a mock function with given fields: ctx, req
func (_m *HttpParseriface) HTTPGet(ctx context.Context, req *http.Request) ([]byte, error) {
	ret := _m.Called(ctx, req)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) []byte); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JSONParse provides a mock function with given fields: ctx, req
func (_m *HttpParseriface) JSONParse(ctx context.Context, req *http.Request) (*map[string]interface{}, error) {
	ret := _m.Called(ctx, req)

	var r0 *map[string]interface{}
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) *map[string]interface{}); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
